In [1]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
base_salario = pd.read_csv("data/salario.csv")

In [3]:
base_salario

idade  salario
0     18      850
1     23     1500
2     28     2000
3     33     2200
4     38     2500
5     43     3500
6     48     3200
7     53     5000
8     58     6000
9     63     3000

# Divisão Dados

In [4]:
X_salario = base_salario.iloc[:, 0].values
X_salario

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64)

In [5]:
y_salario = base_salario.iloc[:, 1].values
y_salario

array([ 850, 1500, 2000, 2200, 2500, 3500, 3200, 5000, 6000, 3000],
      dtype=int64)

# Correlação Variáveis

In [6]:
np.corrcoef(X_salario, y_salario)

array([[1.        , 0.81892113],
       [0.81892113, 1.        ]])

# Formatando em Matriz

In [7]:
X_salario.shape

(10,)

In [8]:
X_salario = X_salario.reshape(-1,1)

In [9]:
X_salario.shape

(10, 1)

# Treinamento Modelo

In [10]:
from sklearn.linear_model import LinearRegression

In [12]:
reg_salario = LinearRegression()
reg_salario.fit(X_salario, y_salario)

LinearRegression()

In [13]:
reg_salario.intercept_

-453.99999999999955

In [14]:
reg_salario.coef_

array([84.66666667])