In [1]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
base_salario = pd.read_csv("data/salario.csv")

In [3]:
base_salario

idade  salario
0     18      850
1     23     1500
2     28     2000
3     33     2200
4     38     2500
5     43     3500
6     48     3200
7     53     5000
8     58     6000
9     63     3000

# Divisão dos Dados

In [4]:
X_salario = base_salario.iloc[:, 0].values
X_salario

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64)

In [5]:
y_salario = base_salario.iloc[:, 1].values
y_salario

array([ 850, 1500, 2000, 2200, 2500, 3500, 3200, 5000, 6000, 3000],
      dtype=int64)

In [6]:
X_salario = X_salario.reshape(-1,1)

# Definindo o número de graus

In [7]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
X_salario_poly = poly.fit_transform(X_salario)

In [8]:
X_salario_poly.shape

(10, 3)

In [9]:
X_salario_poly

array([[1.000e+00, 1.800e+01, 3.240e+02],
       [1.000e+00, 2.300e+01, 5.290e+02],
       [1.000e+00, 2.800e+01, 7.840e+02],
       [1.000e+00, 3.300e+01, 1.089e+03],
       [1.000e+00, 3.800e+01, 1.444e+03],
       [1.000e+00, 4.300e+01, 1.849e+03],
       [1.000e+00, 4.800e+01, 2.304e+03],
       [1.000e+00, 5.300e+01, 2.809e+03],
       [1.000e+00, 5.800e+01, 3.364e+03],
       [1.000e+00, 6.300e+01, 3.969e+03]])

In [10]:
X_salario_poly[0]

array([  1.,  18., 324.])

In [11]:
X_salario_poly[1]

array([  1.,  23., 529.])